name: "Get images info"

on:
  workflow_dispatch:

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: "install libs"
      run: |
        pip install requests
        pip install lxml

    - name: "Run my spider"
      env:
        P_START: 71
        P_END: 140
      run: |
        python index.py

    - name: "Upload Info"
      uses: actions/upload-artifact@master
      with:
        name: info
        path: output